### ISSUE TITLE
Fetch mentix data in real time

### ISSUE THREAD

**Issue by michielbdejong** [sciencemesh/meshdirectory-web#30]
This web app should load the live data directly from https://iop.sciencemesh.uni-muenster.de/iop/mentix/cs3 whenever the user refreshes the page.

Our current loop for debugging our site metadata is:
1. make a change in https://gocdb.sciencemesh.uni-muenster.de/gocdb/index.php
2. wait 4 minutes for https://iop.sciencemesh.uni-muenster.de/iop/mentix/cs3 to reflect the changes
3. wait until @mirekys manually updates the  providers.json on their server.
4. if the result is correct, done
5. if not. go back to 1.

It would be good to remove step 3 from this. :)

**Comment by mirekys** [comment]
I've added an option `PROVIDERS_API`, which, when used, makes meshdirectory-web service completely independent of Reva and changes made in mentix providers api are reflected in almost* realtime in the app, with no manual intervention needed.

\* web app providers list is pre-compiled with [ISR](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration), but it now revalidates the generated page every 1min to ease the debugging
